### ISSUE TITLE
Dispatcher not working with ListenerProviderInterface

### ISSUE THREAD

**Issue by slepic** [phoole/event#1]
Here https://github.com/phoole/event/blob/master/src/Dispatcher.php#L89
you assume that `Psr\EventDispatcher\ListenerProviderInterface` returns `Phoole\Base\Queue\PriorityQueue`
But in fact implementations of that interface may return anything `iterable`.
And so `Phoole\Event\Dispatcher` only works with `Phoole\Event\Provider`, because as far as i know that is the only implementation of  `Psr\EventDispatcher\ListenerProviderInterface` which returns `Phoole\Base\Queue\PriorityQueue`.

**Comment by slepic** [comment]
Btw it also violates [specification of PSR EventDispatcher](https://www.php-fig.org/psr/psr-14/#dispatcher):
> A Dispatcher: MUST call Listeners synchronously in the order they are returned from a ListenerProvider.

**Comment by phoole** [comment]
thanks!
I updated the Dispatcher.php
as for the second comment: dispatcher ACTUALLY calls listeners in order returned from *A* listenerProvider
